[build]
builder = "nixpacks"
buildCommand = "npm install && npx tsx script/build.ts"

[deploy]
startCommand = "node dist/index.cjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
aptPkgs = ["sqlite3"]
